trigger:

- main

pool: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo %NODE_EXTRA_CA_CERTS%
  displayName: 'Where am I?'

- script: |
    go list -f "%GO_TEMPLATE%" -compiled -deps | sort /unique > go.list
  displayName: 'Create go.list file'
    
- task: SonatypeEvaluate@2
  inputs:
    nexusIqService: 'Lifecycle'
    applicationId: 'secman__grealyve'
    stage: 'Build'
    scanTargets: '**/*.jar, **/*.war, **/*.ear, **/*.zip, **/*.tar.gz, **/go.sum, **/go.list, **/Gopkg.lock'
    resultFile: 'lifecycle-output'
    
#- task: FortifySCA@7
#  inputs:
#    applicationType: 'other'
#    buildAnalyzerParams: '-gopath C:\Users\Administrator\go -goroot C:\Program Files\Go'
#    fortifyBuildId: 'secman'
#    fortifyScanType: 'LocalScan'
#    additionalScanParams: ''
#    runFortifyUpload: true
#    fortifyServerName: 'SSC Connection'
#    fortifyApplicationName: 'secman'
#    fortifyApplicationVersion: 'azure'
#    fortifyBuildFailureCriteria: '[fortify priority order]:critical'
#    taskResultForBuildFailureCriteria: 'FAIL'


