trigger:
- main

pool: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo %NODE_EXTRA_CA_CERTS%
    sourceanalyzer -b fullstack -clean
    sourceanalyzer -b fullstack -gopath C:\Users\Administrator\go -goroot C:\Program Files\Go .
    sourceanalyzer -b fullstack "./frontend/**/*.js"
    sourceanalyzer -b fullstack -scan -f fullstack.fpr
  displayName: 'Scan'
