version: '3.8'

services:
  secman:
    build:
      context: .
      dockerfile: DOCKERFILE
    container_name: secman_all_in_one
    restart: always
    ports:
      - "4040:4040"  # Application
      - "5432:5432"  # PostgreSQL
      - "6379:6379"  # Redis
    volumes:
      - postgres_data:/var/lib/postgresql/14/main
      - redis_data:/var/lib/redis
      - app_logs:/var/log/supervisor
    environment:
      - POSTGRES_PASSWORD=lutenix
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4040/health && pg_isready -h localhost -p 5432 -U lutenix && redis-cli ping"]
      interval: 30s
      timeout: 15s
      start_period: 60s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local